### ISSUE TITLE
Pullup necessarie sui pulsanti?

### ISSUE THREAD

**Issue by marcogarzotti** [SukkoPera/AnalogJoystickForArduino#1]
Ciao SukkoPera,
nella foto dei collegamenti elettrici, extras/schematics.png, le resistenze R[5-8] mi pare siano  solo dei semplici pull-up a 5V. Sono necessarie anche con un arduino?
Non posso semplicemente definire i pin DI come pinMode(DI x, INPUT_PULLUP); ed evitare completamente di metterle? (ed evitare di portare un cavi ai 5V ovviamente)
Grazie.

**Comment by SukkoPera** [comment]
La libreria attiva già i pull-up interni, per cui sì, le R5-R8 per i pulsanti non sono necessarie.

In linea di massima, l'immagine è solo per riferimento, non l'ho creata io ma trovata chissà dove :).
